name: Benchmarks
on: [push, pull_request]
jobs:
  deployment:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        working-directory: testing
        run: npm install
      - name: Loading time
        working-directory: testing
        run: node ./benchmarks/loading.js
      - name: Package size
        working-directory: testing
        run: node ./benchmarks/size.js
